homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Kuala_Lumpur
  # Customization file
  customize: !include customize.yaml
    
      
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_gateway
      
#Media Player
media_player:
  - platform: yamaha_musiccast
    host: 192.168.88.177
  - platform: spotify
    client_id: !secret yamaha_client_id
    client_secret: !secret yamaha_client_secret
    aliases:
        abc123def456: 'Living Room'
        9183abas000: 'Bed Room'

#Google Assistance
google_assistant:
  project_id: home-assistant-188314
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  #agent_user_id: leongtat3110@gmail.com
  api_key: !secret ga_api_key
  exposed_domains:
    - switch
    - fan
        
# Enables support for tracking state changes over time
history:

# Light
light:
  - platform: xiaomi_miio
    name: Xiaomi LED 1
    host: 192.168.88.161
    token: b2ad999dfdf9c8572e1d3bf6dd449e74
  - platform: xiaomi_miio
    name: Xiaomi LED 2
    host: 192.168.88.162
    token: 53480382db9f4853d1cd167ce1741791
    
# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: "Weather"
  - platform: broadlink
    update_interval: 60
    host: 192.168.88.182
    mac: !secret broad_rmpro_mac
    monitored_conditions:
      - 'temperature'
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  
# Presence Detection
#device_tracker:
#  - platform: mikrotik
#    host: 192.168.88.1
#    username: !secret mikrotik_username
#    password: !secret mikrotik_password 
#    interval_seconds: 60    

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.88.172
      - 192.168.88.160   
    
#camera
#camera:
#  - platform: yi
#    name: Camera
#    host: '192.168.88.243'
#    password: 1234qwer
#    path: /record

# Text to speech
tts:
  - platform: google

switch: !include switches.yaml      
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
