homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Kuala_Lumpur
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/pi/snapshot  
      
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest
# Enables configuration UI
config:

#panel_iframe:
#  configurator:
#    title: 'Configurator'
#    icon: mdi:wrench
#    url: 'http://leongtat.duckdns.org:3218'

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_gateway
      
#Media Player
media_player:
  - platform: yamaha_musiccast
    host: 192.168.88.177
  - platform: spotify
    client_id: !secret yamaha_client_id
    client_secret: !secret yamaha_client_secret
    aliases:
        abc123def456: 'Living Room'
        9183abas000: 'Bed Room'

cast:
  media_player:
  - host: 192.168.88.196

#Google Assistance
#google_assistant:
#  project_id: !secret ga_project_id
#  client_id: !secret ga_client_id
#  access_token: !secret ga_access_token
  #agent_user_id: leongtat3110@gmail.com
#  api_key: !secret ga_api_key
#  exposed_domains:
#    - switch
#    - fan
        
# Enables support for tracking state changes over time
history:

# Light
light:
  - platform: xiaomi_miio
    name: Xiaomi LED 1
    host: 192.168.88.161
    token: !secret xiaomiled1_key
  - platform: xiaomi_miio
    name: Xiaomi LED 2
    host: 192.168.88.162
    token: !secret xiaomiled2_key
    
# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# weather prediction
weather:
  - platform: darksky
    api_key: !secret darksky_secret
  - platform: yweather
    woeid: 28347209

# Weather prediction
  
# Presence Detection
#device_tracker:
#  - platform: mikrotik
#    host: 192.168.88.1
#    username: !secret mikrotik_username
#    password: !secret mikrotik_password 
#    interval_seconds: 60    

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.88.172
      - 192.168.88.160   

ios:
  push:
    categories:
      - name: CarPorch
        identifier: 'CarPorch'      
        actions:
          - identifier: 'Close_Car_Porch_Gate'
            title: 'Close Car Porch Gate'   
        
        #camera
camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.88.246/ch0_0.h264
    name: Play Area
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.88.154/ch0_0.h264
    name: Garage
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://192.168.88.243/ch0_0.h264
    name: Kitchen
#camera:
#  - platform: yi
#    name: Camera
#    host: '192.168.88.246'
#    password: !secret yi_camera_pass
#    path: /record

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_token
    default_channel: '#homeassistant'
  - name: ios
    platform: ios
    target: !secret ios_notify

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json  
    
# Text to speech
tts:
  - platform: google

switch: !include switches.yaml      
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
climate: !include climate.yaml
sensor: !include sensors.yaml